server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: o0i7Mgrn02sGyxbxBDh7I7of7QSK6XXd
            client-secret: mbZrVM1mtOMW75w2nDNfSLFBoDReVkm2akgr92SqZPqCIa2eZsuQpUy5mFbf6n_a
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://pnpinfos.auth0.com/
